import ManageCandidatesComponent from "./candidates";
import ManageEmployerComponent from "./employer";
import ManageJobsComponent from "./jobs";
import ManageTendersComponent from "./tenders";
import DashboardComponent from "../dashboard";
export const ManageJobs = ManageJobsComponent;
export const ManageTenders = ManageTendersComponent;
export const ManageEmployer = ManageEmployerComponent;
export const ManageCandidate = ManageCandidatesComponent;
export const Dashboard = DashboardComponent;
