import ManageSettingsComponent from "./manageSettings";
import ManageUserRightsComponent from "./manageUserRights";
import ManagePrivacyPolicyComponent from "./managePrivacyPolicy";
import ManageSkillsComponent from "./manageSkills";
import ManageCategoryComponent from "./manageCategory";
import ManageEducationComponent from "./manageEducation";
import ManageCountryComponent from "./manageCountry";
import ManageSectorComponent from "./manageSector";
import ManageTagComponent from "./manageTag";
import ManageLanguageComponent from "./mangeLanguage";
import ManageOpportunity from "./manageOpportunity";

export const ManageSettings = ManageSettingsComponent;
export const ManageUserRights = ManageUserRightsComponent;
export const ManagePrivacyPolicy = ManagePrivacyPolicyComponent;
export const ManageSkills = ManageSkillsComponent;
export const ManageCategory = ManageCategoryComponent;
export const manageEducation = ManageEducationComponent;
export const manageCountry = ManageCountryComponent;
export const manageSector = ManageSectorComponent;
export const manageTag = ManageTagComponent;
export const ManageLanguage = ManageLanguageComponent;
export const manageOpportunity = ManageOpportunity;
